Open VeBus settings if AC input widget is a vebus device
victronenergy/gui-v2 pull request #1136
Opened 2024-05-23 12:54 UTC by jpetrell

Fixes #1026.

2024-05-23 20:15 UTC, jpetrell commented on components/widgets/AcInputWidget.qml
> +		if (root.input.serviceUid.indexOf("com.victronenergy.grid") >= 0 || root.input.serviceUid.indexOf("com.victronenergy.genset") >= 0)  {
> Not sure how to detect when grid meter is available.

Asked Rein if there is a way to detect if there is a grid meter: "think you can rely on the service name starting with com.victronenergy.grid or com.victronenergy.genset (for the generator variant of AC input). systemcalc does it too: # If a grid meter is present we use values from it. If not, we look at the multi".

2024-05-23 20:16 UTC, jpetrell commented
> There are some funky little differences between settings now depending on where you access the multi device, trying to untangle that now.

Should expose now the same data whether opened from the Overview or device list pages.

Filed task https://github.com/victronenergy/gui-v2/issues/1137 for aligning small differences in VeBus and InverterCharger layouts.

2024-05-24 03:35 UTC, blammit requested changes

2024-05-24 03:35 UTC, blammit commented on data/common/AcInputSettingsModel.qml
> +ListModel {
Nice to have this refactored out into AcInputSettingsModel :) 

This could be moved into a separate commit?

2024-05-24 03:35 UTC, blammit commented on data/common/ActiveAcInput.qml
> +	readonly property int mode: _mode.value === undefined ? -1 : _mode.value
I don't think we should add this `mode` property or the `inputSettings` property because they don't make sense for AC inputs. For example, looking at https://github.com/victronenergy/venus/wiki/dbus, `/Ac/NumberOfAcInputs` is only present in `com.victronenergy.multi`, and there is no `/Mode` value for `com.victronenergy.<grid|genset>` services. Ideally the properties in ActiveAcInput.qml are common ones that are generically relevant to AC inputs.

But it shouldn't be necessary to add these properties to try to coerce `ActiveAcInput` to have similar properties to a vebus service, as per comment for `AcInputWidget.qml`.

2024-05-24 03:35 UTC, blammit commented on components/widgets/AcInputWidget.qml
> +		if (root.input.serviceUid.indexOf("com.victronenergy.grid") >= 0 || root.input.serviceUid.indexOf("com.victronenergy.genset") >= 0)  {
There is an easier way to do this, without needing to coerce this `ActiveAcInput` object to fit the `veBusDevice` value in `PageVeBus.qml`. Basically, Global.inverterChargers.veBusDevices is a model of all vebus devices, which means you can find the matching device from there, instead of passing this `input` directly.

So e.g. this change should be sufficient to fix the issue, without the other `data/` changes:

```
if (root.input.serviceType === "vebus") {
    const deviceIndex = Global.inverterChargers.veBusDevices.indexOf(root.input.serviceUid)
    if (deviceIndex >= 0) {
        const veBusDevice = Global.inverterChargers.veBusDevices.deviceAt(deviceIndex)
        Global.pageManager.pushPage( "/pages/vebusdevice/PageVeBus.qml", {
            "title": veBusDevice.name,
            "veBusDevice": veBusDevice
        })
    }
    return
}

// Assume this is on a grid/genset service
Global.pageManager.pushPage("/pages/settings/devicelist/ac-in/PageAcIn.qml", {
    "title": root.input.name,
    "bindPrefix": root.input.serviceUid
})
```
    
We do need some more documentation for `data/` to make this kind of thing more clear.

2024-05-24 04:38 UTC, jpetrell commented on components/widgets/AcInputWidget.qml
> +		if (root.input.serviceUid.indexOf("com.victronenergy.grid") >= 0 || root.input.serviceUid.indexOf("com.victronenergy.genset") >= 0)  {
Cool! I'll do that

2024-05-24 06:09 UTC, jpetrell commented on data/common/AcInputSettingsModel.qml
> +ListModel {
Separated to own commit.

2024-05-24 06:10 UTC, jpetrell commented on data/common/ActiveAcInput.qml
> +	readonly property int mode: _mode.value === undefined ? -1 : _mode.value
No more changes to ActiveAcInput.qml

2024-05-24 06:10 UTC, jpetrell commented
> Global.inverterChargers.veBusDevices is a model of all vebus devices, which means you can find the matching device from there

Done.

2024-05-24 06:13 UTC, blammit approved these changes

2024-05-24 06:54 UTC, merged