Hide controlling BMS setting if BMS is unavailable
victronenergy/gui-v2 pull request #1173
Opened 2024-05-30 12:24 UTC by jpetrell

Fixes #1078.

2024-05-31 00:58 UTC, blammit requested changes

2024-05-31 00:58 UTC, blammit commented on pages/settings/PageSettingsDvcc.qml
> +						 && (bmsOptions.defaultOptionModel.length > 2 || bmsService.isValid)
The `defaultOptionModel` is read-only and always has a length of 2. This should check `bmsOptions.optionModel.length` instead.

2024-05-31 05:36 UTC, jpetrell commented on pages/settings/PageSettingsDvcc.qml
> +						 && (bmsOptions.defaultOptionModel.length > 2 || bmsService.isValid)
Good catch! :coin:  Fixed.

2024-06-05 01:29 UTC, blammit approved these changes

2024-06-07 04:02 UTC, chriadam commented on pages/settings/PageSettingsDvcc.qml
> +						 && (bmsOptions.optionModel.length > 2 || bmsService.isValid)
this > 2 check seems a bit magic to me.  Could a comment be added?

2024-06-10 11:47 UTC, jpetrell commented on pages/settings/PageSettingsDvcc.qml
> +						 && (bmsOptions.optionModel.length > 2 || bmsService.isValid)
Added.

2024-06-10 11:47 UTC, merged