Alternator: Engine Temperature: Added support
victronenergy/gui-v2 pull request #1187
Opened 2024-06-04 22:07 UTC by nmbath

Added support to display engine temperature.

2024-06-04 23:34 UTC, chriadam commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		onHeightChanged: console.trace()
leftover debugging?

2024-06-05 00:43 UTC, DanielMcInnes commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
The change looks good, but I don't see '.../Engine/Temperature' on the bus (I do see '.../Engine/Speed'). Does this need other customized firmware to work?

2024-06-05 11:47 UTC, nmbath commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
Yes this is a new dbus path that has been added through the ve.can driver [here](https://github.com/victronenergy/dbus-vecan/commit/9cb67d8121041330f2257d34b6e84a38bd33b2d2)

2024-06-05 22:58 UTC, DanielMcInnes reviewed
lgtm (once the leftover debugging is removed)

2024-06-13 07:30 UTC, nmbath commented
I have updated to remove the console.trace().

2024-06-14 08:03 UTC, jpetrell commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
Can this be merged? Has the ve.can driver change been included in the existing releases?

2024-06-14 10:18 UTC, nmbath commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
is in the main branch of vecan-dbus, however that has not yet been merged into VenusOS beta. It is on the todo list.

2024-06-17 02:43 UTC, DanielMcInnes approved these changes

2024-07-07 11:46 UTC, msigman commented
I love the idea of displaying the temp on the alternator box. However one suggestion is that alternator temp would likely be more useful than the engine temp for this. Devices like Wakespeed and Zeus have a temperature probe and already make the alternator temp available in the Cerbo.

2024-07-07 12:19 UTC, nmbath commented
Alternator temp is already displayed, as long as it has been supplied by the controller.

2024-07-07 21:57 UTC, msigman commented
> Alternator temp is already displayed, as long as it has been supplied by the controller.
> 
> In all cases this is displayed on the details page.

Understood, makes sense. I was thinking this was adding the temp display on the Overview tile, similar to the battery temp display.  Now I understand you are adding it in the Details page for the alternator. Great addition! 

A separate suggestion then for consideration would be to add the alternator temp to the Overview tile, like the battery temp. I suppose this should be logged as a new issue/feature request.
![IMG_1163](https://github.com/victronenergy/gui-v2/assets/1909816/88968b83-498d-4efe-9ca2-4226fa1155c6)

2024-07-30 04:16 UTC, chriadam commented
@nmbath please ping me or Daniel when the required version of vecan-dbus has made its way into venus, so we can merge this one.  Thanks!

2024-08-20 07:18 UTC, blammit requested changes
Needs an update to the temperature names, as commented.

2024-10-06 16:16 UTC, nmbath commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
@blammit I have differentiated using` sTrId("dc_alternator_temperature")` and `sTrId("alternator_engine_temperature")` however not sure what else is needed to define these strings or where they are defined.

2024-10-08 00:05 UTC, blammit commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
@nmbath it just needs the Engineering English strings, like this:

```
//% "Alternator temperature"
text:  qsTrId("dc_alternator_temperature")
```

and

```
//% "Engine temperature"
text: qsTrId("alternator_engine_temperature")
```

(If those are the strings that should be displayed.)

2024-10-08 07:38 UTC, nmbath commented on pages/settings/devicelist/dc-in/PageAlternatorModel.qml
> +		text: CommonWords.temperature
@blammit Many thanks. Done and pushed an udpate.

2024-10-14 02:48 UTC, blammit approved these changes

2024-10-14 02:49 UTC, merged