Added Tailscale service
victronenergy/gui-v2 pull request #1393
Opened 2024-08-06 16:03 UTC by mr-manuel

The Tailscale service is beeing integrated into Venus OS.

2024-08-06 16:04 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +					// NOTE: To discuss, if this is OK or if it's better to use the QtQrCode library
See https://github.com/victronenergy/gui-v2/issues/1350.

2024-08-07 11:02 UTC, mr-manuel commented
@blammit @DanielMcInnes is it possible to merge this before the next release, so that it is included in the next Venus OS beta release?

2024-08-08 00:26 UTC, blammit reviewed
Is there a VRM installation where this can be tested?

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsServices.qml
> +				visible: tailscale.isValid
Set `allowed` instead of `visible`, as that plays better with delegate resizing in the ListView.

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsServices.qml
> +				text: "Tailscale (remote VPN access)"
Use translation ids, like this: 

```
text: qsTrId("settings_tailscale_remote_vpn_access")
```

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +		var returnValue;
Prefer `let` to `var`. Also below, can you change the code style to use braces and less spacing, like:

```
if (!isRunning) {
    //...
} else if {
```

etc.

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +	function getState ()
Can you put the opening brace on the same line, and remove the extra spacing, like:

```
function getState() {
```

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +			returnValue = "Tailscale control not running"
Use qsTrId() instead of setting this to an untranslated string.

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +	*/
Is this leftover debug?

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +			*/
Leftover debug?

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +				enabled: ! isEnabled
Would prefer less spacing here for consistency within the codebase, i.e. `enabled: !isEnabled`

2024-08-08 00:26 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +				onClicked: commandItem.setValue ('logout')
Place the `onClicked` handler below the property bindings, i.e. after `showAccessLevel: VenusOS.User_AccessType_Installer`

2024-08-08 00:27 UTC, blammit commented
@chriadam could you review this one as well please?

2024-08-08 03:52 UTC, chriadam commented
In general, I think we should hold off on merging this one until we have included QZXing in the build and this page uses it for its QR stuff, rather than calling out to an external web service.  I will hopefully get around to that QZXing integration task next week.

2024-08-08 05:01 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +	property VeQuickItem commandItem: VeQuickItem { uid: root.tailscaleServiceUid + "/GuiCommand" }
You mean maybe like that?
```
VeQuickItem commandItem: VeQuickItem { uid: root.tailscaleServiceUid + "/GuiCommand" }
```

2024-08-08 05:08 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +	property VeQuickItem commandItem: VeQuickItem { uid: root.tailscaleServiceUid + "/GuiCommand" }
No, without the property. Like this if you have the `id`:

```
VeQuickItem { 
    id: commandItem
    uid: root.tailscaleServiceUid + "/GuiCommand" 
}
```

2024-08-08 07:00 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +	property VeQuickItem commandItem: VeQuickItem { uid: root.tailscaleServiceUid + "/GuiCommand" }
No, it's only the lack of experience programming in Qt.

2024-08-08 07:05 UTC, mr-manuel commented
@blammit you can install and test it on your system: https://github.com/mr-manuel/venus-os_TailscaleGX#execute-commands-via-ssh

@chriadam in order to let the community test in the meanwhile, I changed it temporarely that a base64 image is displayed, which is generated locally.

2024-08-09 05:09 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +	VeQuickItem {
Can you place these VeQuickItems further down, so that the file declares things in this order:

- properties
- signals
- functions
- child objects (like these VeQuickItems)

2024-08-09 05:09 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +				allowed: isConnected && Global.systemSettings.accessLevel.value >= VenusOS.User_AccessType_Installer
Instead of this single `allowed` condition, use it with `showAccessLevel`, like:

```
showAccessLevel: VenusOS.User_AccessType_Installer
allowed: defaultAllowed && root.isConnected
```

2024-08-09 05:09 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +		} else if (!isEnabledAndRunning){
Add a space between the `) {` here and elsewhere.

2024-08-09 05:17 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +									placeholderText: qsTrId("settings_tailscale_advertise_routes_placeholder")
Yes, you are right

2024-08-09 05:23 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +	property bool isConnected: connectState == 100 && isEnabledAndRunning
`isEnabledAndRunning` is used two times, should it be replaced anyway?

2024-08-09 05:27 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +				allowed: isConnected && Global.systemSettings.accessLevel.value >= VenusOS.User_AccessType_Installer
This was more a workaround, since there is a bug. I reverted it to the code you mentioned.

2024-08-17 08:48 UTC, mr-manuel commented
Converted to draft, since https://github.com/victronenergy/gui-v2/pull/1410 has to be merged before.

2024-08-29 07:17 UTC, nmbath commented
@blammit Any idea when this might be merged. I am working on adding Tailscale to the main VenusOS build. That means when I integrate tail scale I have to revert to an old WASM file with none of the new capabilities built in. I do see a referencer to waiting for the QZXing component. However, that is only needed to simplify the install process, the rest of this capability is about monitoring and configuring Tailscale. 

Seperating the two cpomponts, this and QZXing and delivering this sooner would be of benefit.

2024-08-30 00:10 UTC, blammit commented
@nmbath I am not sure, this PR is still in draft mode so I assume @mr-manuel is still going to make updates. 

But yes in regards to whether we want to integrate with a third-party for QR code generation before  https://github.com/victronenergy/gui-v2/pull/1410 is completed -- @chriadam @DanielMcInnes any thoughts? What is the status of https://github.com/victronenergy/gui-v2/pull/1410?

2024-08-30 01:51 UTC, chriadam commented
If QR code generation isn't actually needed for this service (i.e. if the QR code doesn't need to be generated dynamically at runtime and is different for each install, but instead can just be pre-generated and shipped) then I agree - we should just finalise this PR and merge it.

Later, once PR#1410 is ready, we can make a one-line change to the code to take QZXing into use for this Tailscale service, if required.

2024-08-30 11:43 UTC, mr-manuel commented
The QR code is dynamically generated and a working workaround is already implemented.

For me you can merge this PR. In the code the change to the `QZXing` library is already prepared.

2024-08-31 17:17 UTC, mr-manuel commented
@blammit I commented out the QR code field in the meanwhile.

2024-09-02 01:54 UTC, DanielMcInnes commented on pages/settings/PageSettingsTailscale.qml
> +	property int connectState: stateItem.isValid ? stateItem.value : 0
`readonly`? For this property, and any others that we don't write to

2024-09-02 02:02 UTC, DanielMcInnes commented on pages/settings/PageSettingsTailscale.qml
> +		let text_cleaned = textField.text.trim().toLowerCase()
lower camel-case for variable names please, eg. `textCleaned`. Here and elsewhere.
[software_-_way_of_working (2).pdf](https://github.com/user-attachments/files/16831429/software_-_way_of_working.2.pdf)

2024-09-02 03:11 UTC, DanielMcInnes approved these changes
A few nits, but lgtm

2024-09-02 04:45 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +	property int connectState: stateItem.isValid ? stateItem.value : 0
Shouldn't `readonly` be used for properties that are not changed after initializing? The `connectState` changes and also the others.

2024-09-02 05:02 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +		let text_cleaned = textField.text.trim().toLowerCase()
Thanks, I did not had that document. I updated the code.

2024-09-02 08:21 UTC, DanielMcInnes commented on pages/settings/PageSettingsTailscale.qml
> +	property int connectState: stateItem.isValid ? stateItem.value : 0
In this case, we are binding `connectState` to the expression `stateItem.isValid ? stateItem.value : 0`. We don't ever assign a new expression or value to it. 

If we make `connectState` a readonly property, eg:
`readonly property int connectState: stateItem.isValid ? stateItem.value : 0`

... it protects us from accidentally changing the value of `connectState`
```
	function getState() {
		if (connectState = 100) {    // bug - I should have written: if (connectState === 100)
			console.log("Initializing")
		}
		...
```

At runtime, we will see an error message like this:
qrc:/qt/qml/Victron/VenusOS/pages/settings/PageSettingsTailscale.qml:67: TypeError: Cannot assign to read-only property "connectState"

Lastly, if we make `connectState` a readonly property, the value of `connectState` can still change at runtime according to the value of `stateItem`. It still behaves the same way.

2024-09-02 09:16 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +	property int connectState: stateItem.isValid ? stateItem.value : 0
Thank you very much for this explanation! Now everything is clear.

2024-09-02 23:42 UTC, blammit requested changes

2024-09-02 23:42 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +									placeholderText: qsTrId("settings_tailscale_local_network_access_custom_networks_placeholder") + " 192.168.1.0/24"
Placing the example IP directly within the engineering english would make it easier for translation. And "e.g.:" is a little harder to read; how about something like this instead?

```
//% "Example: 192.168.1.0/24"
placeholderText: qsTrId("settings_tailscale_local_network_access_custom_networks_placeholder")
```

2024-09-02 23:42 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +				onClicked: commandItem.setValue ('logout')
Remove extra space after `setValue`

2024-09-02 23:42 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +	function _checkAndCleanup(textField, pattern) {
There are some helpers in `ListTextField` now to make it easier to validate the text input, and clean up the text before it is saved. You can use `validateInput` to assign a function that validates the input and show some notification text when validation fails.

I can see here that you want to show a notification even when validation succeeds, to indicate the text needed to be cleaned up.  I've made a PR to make this possible with ListTextField, and added some demo code to show how this can be used: https://github.com/victronenergy/gui-v2/pull/1434

Can you have a look and update this PR to use `validateInput` instead of this custom validation and notification creation? Let me know if you have any issues.

2024-09-02 23:42 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +		if (tailscaleEnabled  && Global.systemSettings.canAccess(VenusOS.User_AccessType_Installer)) {
Extra space after `tailscaleEnabled`

2024-09-02 23:42 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +							showEditNotification()
Should the "Disable Tailscale to edit these settings" text be shown as a ListLabel at the top of this particular page instead, when tailscale is enabled? It seems odd to have a notification appear every time the page is opened.

Same for the other use of `showEditNotification()`.

2024-09-03 00:47 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +							showEditNotification()
I had it before as ListLabel, but @mpvader preferred a notification.

2024-09-03 19:28 UTC, mr-manuel commented
All changes were made. https://github.com/victronenergy/gui-v2/tree/blam/text-validation-warning has to be merged to make the `VenusOS.InputValidation_Result_Warning` work.

2024-09-04 01:37 UTC, blammit approved these changes
Looks much nicer, thanks for reworking the input validation. Some minor comments, but LGTM to merge once https://github.com/victronenergy/gui-v2/pull/1436 is merged.

2024-09-04 01:37 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +				//qsTrId("settings_tailscale_replaced_invalid_characters").arg(text).arg(textCleaned),
Remove leftover comment?

2024-09-04 01:37 UTC, blammit commented on pages/settings/PageSettingsTailscale.qml
> +				// Remove all unallowed characters
unallowed -> disallowed?

2024-09-04 04:53 UTC, mr-manuel commented on pages/settings/PageSettingsTailscale.qml
> +				//qsTrId("settings_tailscale_replaced_invalid_characters").arg(text).arg(textCleaned),
Yes, was leftover from testing. Fixed

2024-09-05 06:00 UTC, mr-manuel commented
@blammit I synced with main and tested The build again. All is working fine. Could you merge now?

2024-09-05 06:20 UTC, merged

2024-09-05 06:24 UTC, chriadam commented
@mr-manuel thanks very much for this, and for your patience while I was distracted with other things!