Device List: Battery page issues
victronenergy/gui-v2 pull request #616
Opened 2023-12-18 11:13 UTC by mr-manuel

Fixes https://github.com/victronenergy/gui-v2/issues/614

2024-01-10 20:09 UTC, mr-manuel commented
@blammit ready for review

2024-01-11 22:56 UTC, blammit requested changes
Thanks for the patches, just have some minor comments. Also would be helpful if you could rebase on top of https://github.com/victronenergy/gui-v2/pull/647 as that changes some of the unit conversion API.

2024-01-11 22:56 UTC, blammit commented on components/settings/ListFirmwareVersionItem.qml
> +		if (format === "vebus" || !version.match(/^[0-9A-F]+$/i))
Use {} for this if statement please.

2024-01-11 22:56 UTC, blammit commented on components/settings/ListFirmwareVersionItem.qml
> +		var hexString = version.toString(16).toUpperCase();
Prefer `const` or `let` to `var`

2024-01-11 22:56 UTC, blammit commented on pages/settings/devicelist/battery/BatteryDetails.qml
> +		DataPoint {
Please rebase against main, and use VeQuickItem instead of DataPoint

2024-01-11 22:56 UTC, blammit commented on pages/settings/devicelist/battery/PageBatteryDetails.qml
> -						unit: Global.systemSettings.temperatureUnit.value
What was the reason for removing the unit?

2024-01-12 06:49 UTC, mr-manuel commented on components/settings/ListFirmwareVersionItem.qml
> +		if (format === "vebus" || !version.match(/^[0-9A-F]+$/i))
should I also add {} to the other if statements in this file?

2024-01-12 06:49 UTC, mr-manuel commented on components/settings/ListFirmwareVersionItem.qml
> +		var hexString = version.toString(16).toUpperCase();
I change it to `let`

2024-01-12 06:54 UTC, mr-manuel commented on pages/settings/devicelist/battery/PageBatteryDetails.qml
> -						unit: Global.systemSettings.temperatureUnit.value
See https://github.com/victronenergy/gui-v2/issues/614#issue-2046182394

The cell ID and therefore the name of the cell is a string that indicates which cell has the temperature. Else it would be `Cell1°`. The unit is only needed for the temperature value in the next line.

2024-01-12 06:54 UTC, mr-manuel commented on pages/settings/devicelist/battery/BatteryDetails.qml
> +		DataPoint {
Done

2024-01-15 05:38 UTC, mr-manuel commented
@blammit ready for merge

2024-01-16 04:10 UTC, blammit requested changes

2024-01-16 04:10 UTC, blammit commented on pages/settings/devicelist/battery/PageBatteryDetails.qml
> +					qsTrId("devicelist_batterydetails_modules_online").arg(details.modulesOnline.value),
This currently shows "undefined online" if the value is not present. Use something like this instead:

```
//: %1 = number of battery modules that are online
//% "%1 online"
details.modulesOnline.value === undefined ? "--" : qsTrId("devicelist_batterydetails_modules_online").arg(details.modulesOnline.value)
```

Same for the offline text.

2024-01-16 04:11 UTC, blammit commented on pages/settings/devicelist/battery/PageBatteryDetails.qml
> -						unit: Global.systemSettings.temperatureUnit.value
Ah, I see, thanks.

2024-01-16 04:14 UTC, blammit commented
@mr-manuel for the commit "Added capacity DataPoint, show units for capacity, firmware version not uppercase if not hex" -- can you refer to VeQuickItem instead of DataPoint, and reduce the first line of the commit to 70 chars?

2024-01-22 03:44 UTC, blammit commented
@mr-manuel thank you, that looks good now. Could you squash the relevant patches together so that the PR only has the three commits? After that I will merge them.

2024-01-22 06:59 UTC, mr-manuel commented
@blammit here you go

2024-01-24 00:21 UTC, blammit approved these changes
LGTM, thanks!

2024-01-24 00:21 UTC, merged