PV Inverter hide phases without values
victronenergy/gui-v2 pull request #653
Opened 2024-01-11 07:44 UTC by mr-manuel

2024-01-11 22:46 UTC, blammit requested changes
f92438ea834e65a516bc5b317e231add3896559a can be removed from the PR

2024-01-11 22:46 UTC, blammit commented on pages/settings/devicelist/ac-in/PageAcInModelDefault.qml
> +				visible: phasePower.valid
If you rebase against `main`, this should now be `phasePower.isValid` instead

2024-01-11 22:46 UTC, blammit commented on pages/settings/devicelist/ac-in/PageAcInModelDefault.qml
> +				visible: dataValid
Should now be `visible: dataItem.isValid`

2024-01-12 10:32 UTC, mr-manuel commented
See https://github.com/victronenergy/gui-v2/pull/617#discussion_r1450149142. Shoud stay as it is.

2024-01-12 10:32 UTC, closed without merging