Destroy closed dialogs
victronenergy/gui-v2 pull request #716
Opened 2024-02-06 12:47 UTC by jpetrell

2024-02-06 22:45 UTC, jpetrell commented
No longer WIP. Tested all the affected dialogs keep working.

2024-02-07 04:01 UTC, blammit requested changes
Nice, looks great. The only problem is that this doesn't load on wasm, and I suspect it's because `Dialog.qml` is a singleton. There's an issue in wasm builds where QML singletons cannot import `Victron.VenusOS`; this is why we have `Global.qml` with a bunch of global-like properties, which refer to a single instance of various types, that can then be referenced by types that import the `Victron.VenusOS` module.

So I think this is fixable by removing `Dialog.qml` and moving the `open()` function into `pages/DialogLayer.qml`, and then we should be able to call `Global.dialogLayer.open()` from everywhere instead.

2024-02-07 07:03 UTC, jpetrell commented on components/Dialog.qml
> +		var dialog = dialogComponent.createObject(Global.dialogLayer)
Yes! I am a bit rusty. :smile: Fixed.

2024-02-07 07:03 UTC, jpetrell commented
Fixed the singleton issue.

2024-02-08 05:03 UTC, blammit commented on pages/DialogLayer.qml
> +		var dialog = dialogComponent.createObject(Global.dialogLayer, properties)
I've been preferring `const` and `let` to the more open-scoped `var`.

2024-02-08 05:04 UTC, blammit approved these changes
Minor comment, otherwise LGTM

2024-02-08 08:57 UTC, merged